### ISSUE TITLE
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c if has-cmd autorun; then autorun /etc/onbuild.d/; fi]: exit code: 1

### ISSUE THREAD

**Issue by BennyTian** [shinsenter/php#109]
Dockerfile:
```
FROM phpfpm-nginx:latest
ENV LANG en_US.UTF-8
ENV TIMEZONE=Asia/Shanghai
RUN echo $TIMEZONE > /etc/timezone
WORKDIR /var/www/html
ADD ./ /var/www/html/

```

Error:
```
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c if has-cmd autorun; then autorun /etc/onbuild.d/; fi]: exit code: 1
```

Buildkit: 0.11.6

**Comment by shinsenter** [comment]
@BennyTian 

I think your issue might be related to this one:
https://github.com/docker/buildx/issues/769

Please the below steps if you are using Docker Desktop:

1. Open Docker Desktop.
2. Click the gear icon in the top right to open the settings menu.
3. From the left-hand navigation, select "General."
4. Scroll down and uncheck the "Use Docker Compose V2" checkbox.

In my case, this resolved the issue.

Alternatively, there are reports that changing "docker-compose build" to "docker compose build" also worked for some people.
