### ISSUE TITLE
env FIX_APP_PATH_PERMISSION=0 is not working

### ISSUE THREAD

**Issue by LittleTrickster** [shinsenter/php#140]
`FIX_APP_PATH_PERMISSION=0` is not working

Mounted html folder chmod permissions are being modified on start and I want them to stay.

**Comment by shinsenter** [comment]
@LittleTrickster 

I think it's not `chmod` but `chown`. This ensures that when you run the web application using the user defined by the `$APP_USER` variable, the processes can read and write files in the web root directory.

Although it is not documented yet, to disable running `chown` when the container starts, please try using `DISABLE_AUTORUN_FIX_OWNER_GROUP=1`.

**Comment by LittleTrickster** [comment]
`DISABLE_AUTORUN_FIX_OWNER_GROUP=1` did not work.

What it does for me `chown $APP_UID:$APP_GID` and `chmod 755` to html folder

**Comment by shinsenter** [comment]
@LittleTrickster 

I will check the startup flows of the Docker images and fix any issues if necessary.

Could you please provide me with more information about the Docker version and the operating system you’re using?

**Comment by shinsenter** [comment]
@LittleTrickster 
Could you help me try pulling the latest Docker images and give it another shot?

**Comment by LittleTrickster** [comment]
@shinsenter
Now it works when `$APP_UID` matches `html` folder owner otherwise, it changes it to `755`.
This is a lot better than it was before.

**Comment by shinsenter** [comment]
@LittleTrickster Thank you for the feedback!
