### ISSUE TITLE
Magento: /run/s6/basedir/scripts/rc.init: fatal: stopping the container.

### ISSUE THREAD

**Issue by leon-zhang-awx** [shinsenter/php#159]
Hello, dear developer
I have run this command: 

```
docker run -p 80:80 -p 443:443 -p 443:443/udp \
    -v ./mymagento4:/var/www/html \
    ghcr.io/shinsenter/magento:php8.3
```

It fails:

nginx version: nginx/1.22.1
2024/10/30 06:41:15 [emerg] 906#906: duplicate location "/" in /etc/nginx/sites-enabled/00-default.conf:18
nginx: configuration file /etc/nginx/nginx.conf test failed
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.

**Comment by shinsenter** [comment]
Hello @leon-zhang-awx,

Thank you for reporting the issue.

I've uploaded a bug fix. I am currently rebuilding all Docker images and it will take a few hours to complete the build, so please wait and try again with the new Docker images once it's done.

Thank you!
