### ISSUE TITLE
Remove index.php routes in CI4

### ISSUE THREAD

**Issue by devslimbr** [shinsenter/php#27]
In your CI4 image, the index.php is mandatory in the urls even when configured for remover in the CI4 settings. I don't know if you have to enable something in apache in your image to have the rewrite. I've tested other CI4 images and haven't seen this issue.

**Comment by shinsenter** [comment]
@devslimbr 

Thank you for your interest and for posting an issue. However, I'm not clear on your Docker settings, as well as whether the mounted directory in the container is an empty directory or has existing source code.

Basically, my latest Docker images won't create an index.php file by themselves. They also don't include the source code of the CI4 framework, but only a small script to help you pull the latest source code when you mount a completely empty directory into the container.

I hope you can provide more information on the setup as well as any error logs if available.

I look forward to your response.

**Comment by devslimbr** [comment]
Hello, no error appears. CI4's default configuration already works without index.php in the routes.
I believe that the problem is in apache, because even changing the .htaccess inside the /public folder has no effect.

I already put a sample project to test already configured and the routes only work if you have the index.php

Example image docker working (removed index.php)
https://hub.docker.com/r/bitnami/codeigniter

In the Home controller, create a hello() example method.
Create a route pointed to this method of type /hello
With your image I can't access localhost:XXXX/home. Only with localhost:XXXX/index.php/home

**Comment by shinsenter** [comment]
@devslimbr 
Thank you for responding quickly!

Due to a lack of free time recently, I haven't had a chance to review your issue yet.
I will get back to you once I have had a chance to review it.

If you are able to create a pull request for it, I would appreciate it and will review and release your pull request.

Best regards.

**Comment by shinsenter** [comment]
@devslimbr 

I have made changes to the configuration settings for Apache in the newest versions of the docker images. Please try downloading the updated images and rebuilding your docker containers to see if this solves the issue you are experiencing.

**Comment by devslimbr** [comment]
Thanks.! Now it's working perfectly
