### ISSUE TITLE
[Bug]: Synology DSM 6.2.4 - Could not initialize random number generator Found /var/run/php/php-fpm.sock!

### ISSUE THREAD

**Issue by olituks** [shinsenter/php#28]
## Issue description
Hello, after a successful setup from Flarum on my Synology the logs show recurrently this error: 
`[Mon May 29 08:48:45.815751 2023] [:crit] [pid 303] (38)Function not implemented: AH00141: Could not initialize random number generator`
Flarum is not accessible but the container is running.

## Environment

- Operating System Version: DSM 6.2.4 last version (not upgradable anymore)
- Docker Version: 20.10.3-0554
- kernel version on my NAS: 
```
sysadmin@iHome:/$ uname -a
Linux iHome 3.10.105 #25556 SMP Tue Mar 21 22:22:21 CST 2023 x86_64 GNU/Linux synology_cedarview_1812+
```
## Steps to reproduce the issue

1.Install Flarum on a Synology DSM 6.2.4 or higher (confirmed in the nextcloud github with DSM 7.x)
2.
3.

## What is expected?
I know the issue is not directly related with your container, but have you any idea how to solve this?

## Additional details / screenshots
You can see the similar issue for phpmyadmin: https://github.com/phpmyadmin/docker/issues/373
The same with nextcloud: https://github.com/nextcloud/docker/issues/1574

**Comment by gingerbeardman** [comment]
I've had this with other docker containers, if you google the error message you'll find lots.

https://github.com/nextcloud/docker/issues/1574#issuecomment-1048244349

The issue is with the way the docker container is packaged.

The easiest solution is to go back to an older version of the docker container before this breaking change. 

The more difficult solution is to try to persuade the owner of the container to look into and fix the problem.

**Comment by shinsenter** [comment]
Hi @gingerbeardman!

Thank you for providing comprehensive information about this issue. As you mentioned, this is not directly related to my Docker image building process, and currently, I haven't found any effective solution to this problem. Therefore, I would appreciate it if you could let me know if there are any possible solutions.

Best regards.

**Comment by gingerbeardman** [comment]
Usually the problem is Apache or OpenSSL. There's a patch to prevent use of /dev/urandom/ which is the first thing I'd recommend checking.

**Comment by olituks** [comment]
@shinsenter The only thing I wish is firsty, warning you about the issue and impact on the DSM community, second if it's doable indeed, checking if OpenSSL or another component can be fixed. Nothing more. =) If not, I have a fall back solution with a Raspberry PI 4. Many thanks in advance, whatever the result :) 

@gingerbeardman Yes it sucks to not have possibility to upgrade old expensive hardware from Synology to the 7.x DSM. But it provide me a good reason to wait a decent price to buy on a new SSD NAS like the Asustor Flashstor.

**Comment by gingerbeardman** [comment]
> OpenSSL or another component can be fixed

Historically OpenSSL recommend developers using urandom during integration of OpenSSL into their projects. But internal /dev/urandom only used by OpenSSL if it's available. 

Since recently (v3) they no longer recommend that. Maybe because of this issue, I'm not sure. 

The problem is, many open source projects missed the memo. And many projects don't understand that /dev/urandom isn't always available.

**Comment by shinsenter** [comment]
I am saving this document as a reference link for the issue.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978045

**Comment by gingerbeardman** [comment]
Also worth mentioning from the same thread

> I think a perfectly valid fix would be to document (in the changelog or 
> elsewhere) that this hard requirement was added, in particular because 
> (IIUC) using getrandom() instead of one of the other codepaths is the 
> choice of the package maintainer. (I.e. this isn't just the result of 
> upstream.) Tracking down what broke and why was mostly tricky because it 
> wasn't documented

**Comment by gingerbeardman** [comment]
one solution is to use `php:8.2-apache-buster` 

from: https://github.com/nextcloud/docker/issues/1574#issuecomment-1660024035

**Comment by shinsenter** [comment]
@olituks @gingerbeardman 

I have pushed the newly built docker images from the official php docker images, I hope they can solve your problem.
https://hub.docker.com/r/shinsenter/php/tags

I am updating the documentation, you can also refer to it here.
https://github.com/shinsenter/php/blob/5.x/README.md
