### ISSUE TITLE
[Bug]: phpfpm-apache:php8.2 not working out-of-the-box

### ISSUE THREAD

**Issue by yapsr** [shinsenter/php#29]
## Issue description
When requesting a php page it shows the PHP source. 

## Environment

- Opertaing System Version: Ubuntu 22.04.3 LTS
- Docker Version: 24.0.6

## Steps to reproduce the issue

Use this docker file:
FROM shinsenter/phpfpm-apache:php8.2

## What is expected?
Requesting a php file in a browser, should return the parsed PHP-code.
It seems the fpm socket is pointing to /run/php/php-fpm.sock
The actual fpm socket is located at /run/php/php8.2-fpm.sock

## Additional details / screenshots
Adding these lines fixes the problem:
ENV PHPFPM_SOCK_PATH=/run/php/php8.2-fpm.sock
RUN a2enconf php8.2-fpm

**Comment by shinsenter** [comment]
@yapsr 

Thank you for reaching out regarding an issue with my Docker images. 

I have checked the Docker image `shinsenter/phpfpm-apache:php8.2` you mentioned, and I didn't find any problem related to the `php-fpm.sock` file path.

<img width="539" alt="Screenshot 2023-09-20 at 10 44 17" src="https://github.com/shinsenter/php/assets/2082119/4e0252c9-ea21-468f-bff2-7d1e7edf88b3">

I will double-check and address the issue if necessary. Afterward, I will promptly release a new bug-fix version.

Best regards.

**Comment by promokit** [comment]
I have the same issue with both 8.1 and 8.2 on the same environment. The solution provided by @yapsr is working for me

**Comment by shinsenter** [comment]
@yapsr @promokit 
Are you customizing any configuration file in the `/etc/apache2/sites-enabled/` or `/etc/apache2/sites-available/` directory within Docker?

**Comment by shinsenter** [comment]
@yapsr @promokit 
I've just released a new version of all Docker images.
Please take a look to see if they can address your issue. Your feedback is greatly appreciated.

Best regards.

**Comment by promokit** [comment]
@shinsenter yes, I have customised vhost file. After update it seems to be working without specifying PHPFPM_SOCK_PATH var

**Comment by shinsenter** [comment]
@promokit Thank you for the feedback.
I think customizing any file in the /etc/apache2/sites-enabled/ directory may lead to the problem, so I fixed it.
