### ISSUE TITLE
[Bug]: Symfony API Platform 502 issue

### ISSUE THREAD

**Issue by Jarzebowsky** [shinsenter/php#31]
## Issue description
I'm using render.com to expose service on Symfony with API Platform (running on free plan). I have managed to generate Dockerfile for that service so it build and deploy as expected. The problem occurs while I run any request from defined API - it returns 502 nginx error. I have done some check's and can't find anywhere more parameters about buffer size for fastcgi (not sure tho if that's the issue as locally I'm working with symfony package with frankenphp and caddy). 

## Environment

- Opertaing System Version:
- Docker Version:

## Steps to reproduce the issue

1. Go to Symfony API Platform swagger page
2. Execute any endpoint request directly from it.

## What is expected?
Request should return correct response.

## Additional details / screenshots
```
*58 upstream sent too big header while reading response header from upstream, client: ::1, server: _, request: "GET /api/users?page=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php-fpm.sock:", host: "<host>", referrer: "https://<host>/api/docs"
``` 
![image](https://github.com/shinsenter/php/assets/10238145/bee0a093-5981-456d-af6e-8aede5c96f30)

**Comment by shinsenter** [comment]
Hi @Jarzebowsky 

There is no specific mechanism in my Docker images to automatically enable profiler programs or adjust the container configuration when the APP_ENV environment variable changes.

Could you please share the docker-compose.xml file and Dockerfile you're using?
