### ISSUE TITLE
Traefik Example for https App

### ISSUE THREAD

**Issue by andreknieriem** [shinsenter/php#33]
HI there. I was wondering if you can make an example for use with traefik. For me it isn't working with traefik. I get 503 errors or redirect loops in an TYPO3 installation. Without traefik it worked. So I think there is an error for me.

**Comment by shinsenter** [comment]
@andreknieriem 
Could you please tell me the content of the error message you received?

**Comment by andreknieriem** [comment]
My error is, that in my application I won't get, that the request was https before. So it comes via https to traefik and after that it says http in my app and I get redirect loops and so on. 

If I do somethink like this:
https://github.com/docker-library/wordpress/issues/412?ref=firsttiger.com#issuecomment-508389289
it works, but I don't want to change files for that as this feels wrong. Any idea/advice? Maybe set a fcgi variable?

**Comment by shinsenter** [comment]
@andreknieriem 

What PHP framework are you currently using?

As far as I know, Traefik can forward all client request headers to your application, so the application can properly recognize the browser's request protocol.
https://doc.traefik.io/traefik/getting-started/faq/#what-are-the-forwarded-headers-when-proxying-http-requests

However, some frameworks (like Laravel) require you to configure a Trusted Proxy IP so it can accurately pass along the HTTP requests sent to the application without needing to redirect back to HTTPS.
E.g: https://laravel.com/docs/10.x/requests#configuring-trusted-proxies

So have you checked if there are similar settings available in the framework you are currently using?

I do not have much information about the infrastructure you are building, and the purpose of my docker images is not focused on advanced settings for Traefik, as you can easily find this information on the internet.

I hope the information I have provided is helpful to you.

**Comment by andreknieriem** [comment]
It was on very framework. Laravel, Symfony, TYPO3, but I think it is a problem with traefik. If I just use your perfect Image, it worked. Thanks a lot!
