### ISSUE TITLE
php:8.3-fpm-apache crash

### ISSUE THREAD

**Issue by zeyadmbk** [shinsenter/php#41]
Hi,
Whenever I try to run php:8.3-fpm-apache it crashes as show in the attached screenshot. This just happened recently as it was work couple days ago.

Thanks in advance.

![CleanShot 2024-01-26 at 20 06 03](https://github.com/shinsenter/php/assets/1600211/382c6312-6d6f-4046-9563-562db1f60525)

**Comment by shinsenter** [comment]
Hi @zeyadmbk 

I apologize for any disruption this may cause. We are rolling out updated docker images based on the official php images. Rest assured we have taken steps to minimize the impact of this change on your existing setup.

Your feedback would be most appreciated, so if you could share your Dockerfile, docker-compose.yml or other customizations, it would help us ensure a smooth transition.

Please let me know if you have any other questions or concerns - we're committed to making this a seamless process.

Best regards.

**Comment by zeyadmbk** [comment]
Hi @shinsenter,

Thanks for the quick response, really appreciate it.

I'm running it without any Dockerfile or docker-compose.yml just straight `docker run shinsenter/php:8.3-fpm-apache`

Thanks again.

**Comment by shinsenter** [comment]
@zeyadmbk 

As we are still optimizing the docker images, updates are quite frequent.

Could you please try pulling the latest version of that docker image and try again?

Also, if it's not too much trouble, could you help me test if you experience any similar issues with other docker image variants on your machine - for example:

- shinsenter/php:8.3-fpm-apache-alpine
- shinsenter/php:8.2-fpm-apache
- shinsenter/php:8.2-fpm-apache-alpine
- etc

**Comment by shinsenter** [comment]
I am working on the new documentation. I hope this helps.
https://github.com/shinsenter/php/blob/5.x/README.md

**Comment by zeyadmbk** [comment]
@shinsenter 

`shinsenter/php:8.2-fpm-apache` and `shinsenter/php:8.1-fpm-apache` producing the same issue. Regarding Apline versions, they seem to work but unfortunately I'm looking for Debian-based distribution. 

Regards.

**Comment by shinsenter** [comment]
@zeyadmbk 

Thank you for the quick response.

It seems we did not catch the bug that occurred in the Debian-based docker builds with Apache. We will look to address this early next week and follow up with you.

I hope you can temporarily use the Alpine version for development, as well as let us know if there are any points for improvement with the new docker image versions.

Any feedback is very helpful.

Best regards

**Comment by zeyadmbk** [comment]
@shinsenter 

Looking forward for your update.

Keep up the good, you are doing an amazing job .

Regards.

**Comment by Tassleh0ff** [comment]
Confirmed also for phpfpm-apache:php8.1.
I'm using the image with digest
`shinsenter/phpfpm-apache@sha256:5b446c5d4e11a966a111003e1c33260e2401b2593ef4326e10a45236ab11120d`

Thanks again for your time and work, let me know If I can make something to help you, some test of some debug parameter.

Best regards.

    www-web          |
    www-web          |      _     _                      _              __    _
    www-web          |     | |   (_)                    | |            / /   | |
    www-web          |  ___| |__  _ _ __  ___  ___ _ __ | |_ ___ _ __ / / __ | |__  _ __
    www-web          | / __| '_ \| | '_ \/ __|/ _ \ '_ \| __/ _ \ '__/ / '_ \| '_ \| '_ \
    www-web          | \__ \ | | | | | | \__ \  __/ | | | ||  __/ | / /| |_) | | | | |_) |
    www-web          | |___/_| |_|_|_| |_|___/\___|_| |_|\__\___|_|/_/ | .__/|_| |_| .__/
    www-web          |                                                 | |         | |
    www-web          |                                                 |_|         |_|
    www-web          |
    www-web          |  Github:    https://code.shin.company/php
    www-web          |  DockerHub: https://docker.shin.company/php
    www-web          |
    www-web          |  (To edit this welcome message, add your text to /etc/welcome.txt)
    www-web          |
    www-web          | ----------------------------------------
    www-web          | Container : shinsenter/php
    www-web          | Distro    : Debian GNU/Linux 12 (bookworm)
    www-web          | Timezone  : UTC (GMT+0000)
    www-web          | UID / GID : www-data:www-data (33:33)
    www-web          | Web Root  : /var/www/html
    www-web          | ----------------------------------------
    www-web          |
    www-web          | Copyright (C) 2022-2024 shin@shin.company
    www-web          | This program comes with ABSOLUTELY NO WARRANTY.
    www-web          | This is free software, and you are welcome
    www-web          | to redistribute it under certain conditions.
    www-web          |
    www-web          | To get support, please contact: shin@shin.company
    www-web          |
    www-web          | PHP 8.1.27 (fpm-fcgi) (built: Jan 11 2024 05:26:34)
    www-web          | Copyright (c) The PHP Group
    www-web          | Zend Engine v4.1.27, Copyright (c) Zend Technologies
    www-web          |     with Zend OPcache v8.1.27, Copyright (c), by Zend Technologies
    www-web          | Composer version 2.6.6 2023-12-08 18:32:26
    www-web          |
    www-web          |
    www-web          | Server version: Apache/2.4.57 (Debian)
    www-web          | Server built:   2023-04-13T03:26:51
    www-web          |
    www-web          | AH00534: apache2: Configuration error: No MPM loaded.
    www-web          | AH00534: apache2: Configuration error: No MPM loaded.
    www-web          | cont-init: warning: some scripts exited nonzero
    www-web          | s6-rc: warning: unable to start service legacy-cont-init: command exited 1
    www-web          | /run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in     /run/uncaught-logs/current if you have in-container logging) for more information.
    www-web          | /run/s6/basedir/scripts/rc.init: fatal: stopping the container.

**Comment by shinsenter** [comment]
@zeyadmbk @Tassleh0ff 

I have pushed new Docker images for fpm-apache. Please help me check to see if your issue has been revolved.

Best regards

**Comment by zeyadmbk** [comment]
@shinsenter 

I'm able to run it now without crashing but it keeps printing the following in the logs infinitely:
```
2024-01-28 11:21:20 Usage: apache2 [-D name] [-d directory] [-f file]
2024-01-28 11:21:20                [-C "directive"] [-c "directive"]
2024-01-28 11:21:20                [-k start|restart|graceful|graceful-stop|stop]
2024-01-28 11:21:20                [-v] [-V] [-h] [-l] [-L] [-t] [-T] [-S] [-X]
2024-01-28 11:21:20 Options:
2024-01-28 11:21:20   -D name            : define a name for use in <IfDefine name> directives
2024-01-28 11:21:20   -d directory       : specify an alternate initial ServerRoot
2024-01-28 11:21:20   -f file            : specify an alternate ServerConfigFile
2024-01-28 11:21:20   -C "directive"     : process directive before reading config files
2024-01-28 11:21:20   -c "directive"     : process directive after reading config files
2024-01-28 11:21:20   -e level           : show startup errors of level (see LogLevel)
2024-01-28 11:21:20   -E file            : log startup errors to file
2024-01-28 11:21:20   -v                 : show version number
2024-01-28 11:21:20   -V                 : show compile settings
2024-01-28 11:21:20   -h                 : list available command line options (this page)
2024-01-28 11:21:20   -l                 : list compiled in modules
2024-01-28 11:21:20   -L                 : list available configuration directives
2024-01-28 11:21:20   -t -D DUMP_VHOSTS  : show parsed vhost settings
2024-01-28 11:21:20   -t -D DUMP_RUN_CFG : show parsed run settings
2024-01-28 11:21:20   -S                 : a synonym for -t -D DUMP_VHOSTS -D DUMP_RUN_CFG
2024-01-28 11:21:20   -t -D DUMP_MODULES : show all loaded modules 
2024-01-28 11:21:20   -M                 : a synonym for -t -D DUMP_MODULES
2024-01-28 11:21:20   -t -D DUMP_INCLUDES: show all included configuration files
2024-01-28 11:21:20   -t                 : run syntax check for config files
2024-01-28 11:21:20   -T                 : start without DocumentRoot(s) check
2024-01-28 11:21:20   -X                 : debug mode (only one worker, do not detach)
```
Also, apache server is not running.

Regards.

**Comment by zeyadmbk** [comment]
@shinsenter 

I just tried the Alpine version `shinsenter/php:8.3-fpm-apache-alpine` and it has the same issue as mentioned above.

Regards.

**Comment by shinsenter** [comment]
@zeyadmbk I have fixed the error above. Thank you for your prompt feedback.

**Comment by Tassleh0ff** [comment]
Regarding phpfpm-apache:php8.1 I updated my containers using images with digest

    shinsenter/phpfpm-apache@sha256:70eae50fbfccfa951bfb61d26a132196b0dd173ae7440660a115a944eefe6903

And now everything is ok.

Thank you very much!

**Comment by zeyadmbk** [comment]
@shinsenter 
It is working now.

Thanks a lot. Really appreciate it.

Regards.

**Comment by shinsenter** [comment]
Thank you guys.
