### ISSUE TITLE
[BUG] Unable to view generated PDF in crater

### ISSUE THREAD

**Issue by jcollas** [shinsenter/php#44]
Looks like a php-fpm.sock issue.  This worked fine with the image from January.

Using the image 'shinsenter/crater:php8.1-tidy'

2024/02/01 11:58:40 [crit] 1934#1934: *5 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 10.42.2.35, server: localhost, request: "GET /invoices/pdf/ODR8nvGjg82gLqp4m26r HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "crater", referrer: "https://crater/admin/invoices/23/view"

**Comment by shinsenter** [comment]
@jcollas 

Thank you for sending feedback about our docker images.

We have taken note of and addressed the issue you mentioned. The docker images with the bug fix will be queued for rebuilding in a few hours. Please bear with us while waiting.

Best regards.

**Comment by jcollas** [comment]
Ok, this looks like it's fixed with the images dated 2024-02-02.  Thanks for the quick fix.
