### ISSUE TITLE
Autorun scripts no longer running from WORKDIR path?

### ISSUE THREAD

**Issue by mlantz7** [shinsenter/php#57]
When my "startup" scripts run (from the /startup folder), it used to be relative to the APP_PATH (I use `WORKDIR $APP_PATH` as the last line in my Dockerfile). But I noticed yesterday in some other testing that my scripts were failing to find files I was accessing. I went ahead and added cd $APP_PATH to the top of my script and that resolved my issue.

So, I guess at some point in some of your recent updates, something changed and the process is no longer in WORKDIR when the startup scripts run?

**Comment by shinsenter** [comment]
Hi @mlantz7 

I updated new docker images with some snall fixes. Please try pulling the latest images and help me verify if it has resolved your issue.
