### ISSUE TITLE
AH01630: client denied by server configuration

### ISSUE THREAD

**Issue by runelanghelle** [shinsenter/php#59]
# Issue: Apache Serving .html Files as "Forbidden" in Docker Image

## Description
I've encountered an issue with the `shinsenter/php` Docker image, where `.html` files result in a "Forbidden" error, while `.php` files are served as expected. It's unclear if this behavior is by design or an oversight.

## Appreciation
Firstly, I want to express my gratitude for the effort put into creating and maintaining these images. Your work greatly facilitates our development processes, and it is much appreciated.

## Environment
- Docker version: **Docker version 25.0.3, build 4debf41**
- Image version/tag: **shinsenter/php:8.2-fpm-apache**
- Host OS:  **Ubuntu 22.04.4 LTS**

## Expected vs. Actual Behavior
**Expected:** Both `.php` and `.html` files should be served without issue.
**Actual:** `.html` files result in a "AH01630: client denied by server configuration" response, indicating a potential configuration issue.

## Steps to Reproduce
1. Use the latest `shinsenter/php:8.2-fpm-apache` image.
2. Include `.php` and `.html` files in the web directory.
3. Attempt to access an `.html` file through a browser.

## Clarification Requested
Could you please clarify if the "Forbidden" status for `.html` files is intended? Any guidance on serving `.html` files or a potential fix would be greatly appreciated.

Thank you for your ongoing support and dedication to the community.

**Comment by shinsenter** [comment]
Hi @runelanghelle 

Thank you for detailing the error and I have also confirmed it is a small bug in my Apache2 settings. I have pushed a fix and the Docker images with this patch will be updated tomorrow. Please be patient and wait.

Best regards

**Comment by runelanghelle** [comment]
Thanks for the quick reply, and quick fix!
