### ISSUE TITLE
crater deployment can't record a new payment

### ISSUE THREAD

**Issue by jcollas** [shinsenter/php#80]
When attempting to record a payment, the following errors display:

This is just from going to an invoice and clicking the 'Save Payment' button.  This worked correctly less than a month ago.

![Screenshot 2024-07-19 at 8 32 55 AM](https://github.com/user-attachments/assets/a7a4f176-7b40-45be-b5db-75687f8195ef)

**Comment by shinsenter** [comment]
@jcollas 

I will review and reproduce the issue. In the meantime, please try using the deprecated docker image.

**Comment by jcollas** [comment]
Will do, and thanks for your quick response.

**Comment by shinsenter** [comment]
Hello @jcollas 

I haven't been able to reproduce the issue you encountered with the Crater container, but I did discover that other containers running phpMyAdmin also had problems writing files to the /tmp directory. I have fixed this issue and updated the new Docker images.

While I haven't been able to replicate your issue, could you please try pulling the new (non-deprecated) Docker images and see if this resolves the issue?

**Comment by replete** [comment]
Aha, I had a strange issue recently to do with /tmp access that resulted in 500 errors using glide in Statamic. I've been going bananas trying to make sense of it, but it's started working again:

```
2024-07-19 17:55:07] production.ERROR: tempnam(): file created in the system's temporary directory {"exception":"[object] (ErrorException(code: 0): tempnam(): file created in the system's temporary directory at /var/www/html/vendor/league/glide/src/Server.php:680)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(256): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/league/glide/src/Server.php(680): tempnam()
#3 /var/www/html/vendor/statamic/cms/src/Imaging/ImageGenerator.php(259): League\\Glide\\Server->makeImage()
#4 /var/www/html/vendor/statamic/cms/src/Imaging/ImageGenerator.php(167): Statamic\\Imaging\\ImageGenerator->generate()
#5 /var/www/html/vendor/statamic/cms/src/Imaging/ImageGenerator.php(150): Statamic\\Imaging\\ImageGenerator->doGenerateByAsset()
...
```

**Comment by jcollas** [comment]
Just checked with the new non-deprecated image, and crater's now working again as expected.  Nicely done, thanks,

**Comment by shinsenter** [comment]
Great! Thank you!
